import { Language } from './types';

const translations = {
  en: {
    header: {
      language: 'EN',
    },
    footer: {
      contact: 'Looking for something else? Contact us',
      location: 'MOROCCO 25',
    },
    categories: {
      household: ['Household', 'Services'],
      personal: ['Personal', 'Services'],
      event: ['Event', 'Services'],
      transportation: ['Transportation', 'Services'],
      educational: ['Educational', 'Services'],
      professional: ['Professional', 'Services'],
      health: ['Health and', 'Wellness'],
      technology: ['Technology', 'Services'],
      creative: ['Creative', 'Services'],
    },
    services: {
        custom: { name: 'Custom Request', description: 'Your special request for a service not listed.' },
        h1: { name: 'House Cleaning', description: 'Let us make your home sparkle, from top to bottom.' },
        h2: { name: 'Laundry and Dry Cleaning', description: 'Fresh, clean clothes delivered right to your door.' },
        h3: { name: 'Gardening and Landscaping', description: 'Transform your outdoor space into a beautiful oasis.' },
        h4: { name: 'Handyman Services', description: 'No job is too small for our skilled handy-people.' },
        h5: { name: 'Pest Control', description: 'Quick and effective solutions for a pest-free home.' },
        h6: { name: 'Interior Design', description: 'Let\'s create a space that truly feels like you.' },
        p1: { name: 'Personal Training', description: 'Achieve your fitness goals with a dedicated expert.' },
        p2: { name: 'Massage Therapy', description: 'Relax, unwind, and rejuvenate your body and mind.' },
        p3: { name: 'Personal Shopping', description: 'Your style, curated and delivered by a fashion pro.' },
        p4: { name: 'Beauty and Spa Services', description: 'Indulge in some well-deserved pampering.' },
        p5: { name: 'Pet Grooming', description: 'Happy pets, happy life! Professional grooming for your furry friend.' },
        e1: { name: 'Event Planning', description: 'From start to finish, we\'ll make your event unforgettable.' },
        e2: { name: 'Catering', description: 'Delicious food that will be the talk of the party.' },
        e3: { name: 'Photography and Videography', description: 'Capturing your precious moments beautifully.' },
        e4: { name: 'DJ and Music Services', description: 'Setting the perfect vibe for any occasion.' },
        e5: { name: 'Venue Decoration', description: 'Transforming any space into your dream venue.' },
        t1: { name: 'Car Wash and Detailing', description: 'Get your car looking brand new, inside and out.' },
        t2: { name: 'Ride-Sharing and Carpooling', description: 'Convenient and eco-friendly rides when you need them.' },
        t3: { name: 'Moving and Packing Services', description: 'A smooth, stress-free move handled by professionals.' },
        t4: { name: 'Bike Repair and Maintenance', description: 'Get your bike back on the road in top condition.' },
        ed1: { name: 'Tutoring and Homework Help', description: 'Friendly support to help students succeed.' },
        ed2: { name: 'Language Lessons', description: 'Unlock a new world by learning a new language.' },
        ed3: { name: 'Music Lessons', description: 'Discover your inner musician with expert guidance.' },
        ed4: { name: 'Art and Craft Classes', description: 'Unleash your creativity in a fun, inspiring class.' },
        pr1: { name: 'Legal Consultation', description: 'Clear, expert legal advice you can trust.' },
        pr2: { name: 'Accounting and Bookkeeping', description: 'Let us handle the numbers so you can focus on your business.' },
        pr3: { name: 'Business Consulting', description: 'Strategic insights to help your business grow.' },
        pr4: { name: 'Graphic Design and Branding', description: 'Create a stunning brand identity that stands out.' },
        hw1: { name: 'Nutrition and Diet Counseling', description: 'A personalized plan for a healthier, happier you.' },
        hw2: { name: 'Yoga and Meditation Classes', description: 'Find your balance and inner peace with our classes.' },
        hw3: { name: 'Home Nursing Care', description: 'Compassionate and professional care at home.' },
        hw4: { name: 'Therapist and Counseling Services', description: 'Confidential support for your mental well-being.' },
        tech1: { name: 'IT Support and Repair', description: 'Fast and reliable solutions for your tech troubles.' },
        tech2: { name: 'Web Development and Design', description: 'Building the beautiful, functional website of your dreams.' },
        tech3: { name: 'Digital Marketing', description: 'Grow your online presence and reach more customers.' },
        tech4: { name: 'App Development', description: 'Bring your brilliant app idea to life with our team.' },
        c1: { name: 'Custom Cake Making', description: 'Delicious, custom-designed cakes for any celebration.' },
        c2: { name: 'Tailoring and Alterations', description: 'Perfectly fitted clothes, just for you.' },
        c3: { name: 'Interior Decorating', description: 'Refresh your space with a professional creative touch.' },
        c4: { name: 'Art Commissions', description: 'Own a unique piece of art created just for you.' },
    },
    serviceList: {
      back: 'Back to Categories',
      request: 'Request',
    },
    detailsForm: {
      back: 'Back to Services',
      title: 'Please provide the details for your service request.',
      locationLabel: 'Location',
      locationPlaceholder: 'e.g., 123 Main St, Casablanca',
      dateLabel: 'Date',
      timeLabel: 'Time',
      notesLabel: 'Comments / Special Notes',
      notesPlaceholder: 'e.g., Please bring your own cleaning supplies.',
      photoLabel: 'Upload Photo (Optional)',
      photoButton: 'Choose file',
      submit: 'Get Quote',
    },
    customRequestForm: {
      back: 'Back to Categories',
      title: 'Custom Service Request',
      subtitle: 'Can\'t find what you need? Describe it below and we\'ll get back to you with a quote.',
      notesLabel: 'Describe the service you need',
      notesPlaceholder: 'Please be as detailed as possible...',
      photoLabel: 'Upload Photo (Optional)',
      photoButton: 'Choose file',
      submit: 'Submit Custom Request',
    },
    awaitingQuote: {
      title: 'Request Received!',
      subtitle: 'We are preparing your quote and will notify you shortly when it is ready. This may take a few moments.',
    },
    quote: {
        title: 'Your Quote is Ready!',
        subtitle: 'Please review the details below. To confirm, please make a bank transfer for the advance payment.',
        service: 'Service',
        whenWhere: 'When & Where',
        totalPrice: 'Total Price',
        timeframe: 'Estimated timeframe',
        depositTitle: 'Bank Transfer Details',
        depositInstructions: 'Please transfer the total amount to the following bank account:',
        ribLabel: 'Account Number (RIB)',
        ribNumber: '99089786768688',
        confirmButton: 'I Have Made the Transfer',
    },
    confirmed: {
        title: 'Booking Confirmed!',
        subtitle: 'Thank you for your payment. We will contact you shortly via the app or phone with your assigned provider\'s details. You will now be returned to the home screen.',
    },
    profile: {
        back: 'Back to Home',
        title: 'My Profile',
        totalOrders: 'Total Orders',
        loginTitle: 'Login or Sign Up',
        emailLabel: 'Email Address',
        passwordLabel: 'Password',
        loginButton: 'Login',
        logoutButton: 'Logout',
        or: 'OR',
        google: 'Continue with Google',
        facebook: 'Continue with Facebook'
    }
  },
  fr: {
    header: {
      language: 'FR',
    },
    footer: {
      contact: 'Vous cherchez autre chose ? Contactez-nous',
      location: 'MAROC 25',
    },
    categories: {
      household: ['Services', 'Ménagers'],
      personal: ['Services', 'Personnels'],
      event: ['Services', 'Événementiels'],
      transportation: ['Services de', 'Transport'],
      educational: ['Services', 'Éducatifs'],
      professional: ['Services', 'Professionnels'],
      health: ['Santé et', 'Bien-être'],
      technology: ['Services', 'Technologiques'],
      creative: ['Services', 'Créatifs'],
    },
    services: {
        custom: { name: 'Demande Personnalisée', description: 'Votre demande spéciale pour un service non listé.' },
        h1: { name: 'Nettoyage de maison', description: 'Laissez-nous faire briller votre maison, de fond en comble.' },
        h2: { name: 'Blanchisserie et Nettoyage à sec', description: 'Des vêtements frais et propres livrés à votre porte.' },
        h3: { name: 'Jardinage et Aménagement paysager', description: 'Transformez votre espace extérieur en une belle oasis.' },
        h4: { name: 'Services de bricolage', description: 'Aucun travail n\'est trop petit pour nos bricoleurs qualifiés.' },
        h5: { name: 'Lutte antiparasitaire', description: 'Solutions rapides et efficaces pour une maison sans parasites.' },
        h6: { name: 'Design d\'intérieur', description: 'Créons un espace qui vous ressemble vraiment.' },
        p1: { name: 'Entraînement personnel', description: 'Atteignez vos objectifs de fitness avec un expert dédié.' },
        p2: { name: 'Massothérapie', description: 'Détendez-vous, relaxez-vous et rajeunissez votre corps et votre esprit.' },
        p3: { name: 'Shopping personnel', description: 'Votre style, organisé et livré par un pro de la mode.' },
        p4: { name: 'Services de beauté et spa', description: 'Offrez-vous des soins bien mérités.' },
        p5: { name: 'Toilettage pour animaux', description: 'Animaux heureux, vie heureuse ! Toilettage professionnel pour votre ami à quatre pattes.' },
        e1: { name: 'Planification d\'événements', description: 'Du début à la fin, nous rendrons votre événement inoubliable.' },
        e2: { name: 'Service traiteur', description: 'Des plats délicieux qui feront parler d\'eux.' },
        e3: { name: 'Photographie et Vidéographie', description: 'Capturez magnifiquement vos moments précieux.' },
        e4: { name: 'Services de DJ et musique', description: 'Créez l\'ambiance parfaite pour toute occasion.' },
        e5: { name: 'Décoration de salle', description: 'Transformez n\'importe quel espace en lieu de vos rêves.' },
        t1: { name: 'Lavage et Esthétique auto', description: 'Redonnez à votre voiture un aspect neuf, intérieur et extérieur.' },
        t2: { name: 'Covoiturage', description: 'Des trajets pratiques et écologiques quand vous en avez besoin.' },
        t3: { name: 'Services de déménagement et d\'emballage', description: 'Un déménagement en douceur et sans stress, géré par des professionnels.' },
        t4: { name: 'Réparation et Entretien de vélos', description: 'Remettez votre vélo en parfait état de marche.' },
        ed1: { name: 'Tutorat et Aide aux devoirs', description: 'Un soutien amical pour aider les élèves à réussir.' },
        ed2: { name: 'Cours de langues', description: 'Ouvrez-vous à un nouveau monde en apprenant une nouvelle langue.' },
        ed3: { name: 'Cours de musique', description: 'Découvrez le musicien qui est en vous avec des conseils d\'experts.' },
        ed4: { name: 'Cours d\'art et d\'artisanat', description: 'Libérez votre créativité dans un cours amusant et inspirant.' },
        pr1: { name: 'Consultation juridique', description: 'Des conseils juridiques clairs et experts auxquels vous pouvez faire confiance.' },
        pr2: { name: 'Comptabilité et Tenue de livres', description: 'Laissez-nous gérer les chiffres pour que vous puissiez vous concentrer sur votre entreprise.' },
        pr3: { name: 'Conseil aux entreprises', description: 'Des informations stratégiques pour aider votre entreprise à se développer.' },
        pr4: { name: 'Design graphique et Image de marque', description: 'Créez une identité de marque époustouflante qui se démarque.' },
        hw1: { name: 'Conseils en nutrition et diététique', description: 'Un plan personnalisé pour une vie plus saine et plus heureuse.' },
        hw2: { name: 'Cours de yoga et de méditation', description: 'Trouvez votre équilibre et votre paix intérieure grâce à nos cours.' },
        hw3: { name: 'Soins infirmiers à domicile', description: 'Des soins compatissants et professionnels à domicile.' },
        hw4: { name: 'Services de thérapie et de conseil', description: 'Un soutien confidentiel pour votre bien-être mental.' },
        tech1: { name: 'Support et Réparation informatique', description: 'Des solutions rapides et fiables pour vos problèmes techniques.' },
        tech2: { name: 'Développement et Conception web', description: 'Construisez le site web beau et fonctionnel de vos rêves.' },
        tech3: { name: 'Marketing numérique', description: 'Développez votre présence en ligne et touchez plus de clients.' },
        tech4: { name: 'Développement d\'applications', description: 'Donnez vie à votre brillante idée d\'application avec notre équipe.' },
        c1: { name: 'Création de gâteaux personnalisés', description: 'De délicieux gâteaux conçus sur mesure pour toute célébration.' },
        c2: { name: 'Couture et Retouches', description: 'Des vêtements parfaitement ajustés, juste pour vous.' },
        c3: { name: 'Décoration d\'intérieur', description: 'Rafraîchissez votre espace avec une touche créative professionnelle.' },
        c4: { name: 'Commandes d\'œuvres d\'art', description: 'Possédez une œuvre d\'art unique créée juste pour vous.' },
    },
    serviceList: {
      back: 'Retour aux catégories',
      request: 'Demander',
    },
    detailsForm: {
      back: 'Retour aux services',
      title: 'Veuillez fournir les détails de votre demande de service.',
      locationLabel: 'Lieu',
      locationPlaceholder: 'ex: 123 Rue Principale, Casablanca',
      dateLabel: 'Date',
      timeLabel: 'Heure',
      notesLabel: 'Commentaires / Notes spéciales',
      notesPlaceholder: 'ex: Veuillez apporter vos propres produits de nettoyage.',
      photoLabel: 'Télécharger une photo (Optionnel)',
      photoButton: 'Choisir un fichier',
      submit: 'Obtenir un devis',
    },
    customRequestForm: {
      back: 'Retour aux catégories',
      title: 'Demande de Service Personnalisé',
      subtitle: 'Vous ne trouvez pas ce que vous cherchez ? Décrivez-le ci-dessous et nous vous enverrons un devis.',
      notesLabel: 'Décrivez le service dont vous avez besoin',
      notesPlaceholder: 'Veuillez être aussi détaillé que possible...',
      photoLabel: 'Télécharger une photo (Optionnel)',
      photoButton: 'Choisir un fichier',
      submit: 'Envoyer la Demande Personnalisée',
    },
    awaitingQuote: {
        title: 'Demande Reçue !',
        subtitle: 'Nous préparons votre devis et vous informerons dès qu\'il sera prêt. Cela peut prendre quelques instants.',
    },
    quote: {
        title: 'Votre devis est prêt !',
        subtitle: 'Veuillez vérifier les détails ci-dessous. Pour confirmer, veuillez effectuer un virement bancaire pour l\'acompte.',
        service: 'Service',
        whenWhere: 'Quand & Où',
        totalPrice: 'Prix Total',
        timeframe: 'Durée estimée',
        depositTitle: 'Détails du Virement Bancaire',
        depositInstructions: 'Veuillez virer le montant total sur le compte bancaire suivant :',
        ribLabel: 'Numéro de Compte (RIB)',
        ribNumber: '99089786768688',
        confirmButton: 'J\'ai effectué le virement',
    },
    confirmed: {
        title: 'Réservation confirmée !',
        subtitle: 'Merci pour votre paiement. Nous vous contacterons sous peu via l\'application ou par téléphone avec les détails de votre prestataire. Vous allez maintenant être redirigé vers l\'accueil.',
    },
    profile: {
        back: 'Retour à l\'accueil',
        title: 'Mon Profil',
        totalOrders: 'Commandes totales',
        loginTitle: 'Connexion ou Inscription',
        emailLabel: 'Adresse e-mail',
        passwordLabel: 'Mot de passe',
        loginButton: 'Connexion',
        logoutButton: 'Déconnexion',
        or: 'OU',
        google: 'Continuer avec Google',
        facebook: 'Continuer avec Facebook'
    }
  },
  ar: {
    header: {
      language: 'AR',
    },
    footer: {
      contact: 'هل تبحث عن شيء آخر؟ تواصل معنا',
      location: 'المغرب 25',
    },
    categories: {
      household: ['خدمات', 'منزلية'],
      personal: ['خدمات', 'شخصية'],
      event: ['خدمات', 'المناسبات'],
      transportation: ['خدمات', 'النقل'],
      educational: ['خدمات', 'تعليمية'],
      professional: ['خدمات', 'مهنية'],
      health: ['الصحة و', 'العافية'],
      technology: ['خدمات', 'تقنية'],
      creative: ['خدمات', 'إبداعية'],
    },
    services: {
        custom: { name: 'طلب مخصص', description: 'طلبك الخاص لخدمة غير مدرجة.' },
        h1: { name: 'تنظيف المنازل', description: 'دعنا نجعل منزلك يلمع من الأعلى إلى الأسفل.' },
        h2: { name: 'غسيل وكي الملابس', description: 'ملابس نظيفة ومنعشة تصل إلى باب منزلك.' },
        h3: { name: 'البستنة وتنسيق الحدائق', description: 'حوّل مساحتك الخارجية إلى واحة جميلة.' },
        h4: { name: 'خدمات الصيانة العامة', description: 'لا توجد مهمة صغيرة جدًا على عمالنا المهرة.' },
        h5: { name: 'مكافحة الحشرات', description: 'حلول سريعة وفعالة لمنزل خالٍ من الآفات.' },
        h6: { name: 'تصميم داخلي', description: 'لنصمم مساحة تعبر عنك حقًا.' },
        p1: { name: 'تدريب شخصي', description: 'حقق أهدافك الرياضية مع خبير متخصص.' },
        p2: { name: 'علاج بالمساج', description: 'استرخِ وهدئ أعصابك وجدد شباب جسمك وعقلك.' },
        p3: { name: 'تسوق شخصي', description: 'أسلوبك الخاص، يختاره لك ويوصله خبير أزياء.' },
        p4: { name: 'خدمات التجميل والسبا', description: 'دلل نفسك ببعض العناية التي تستحقها.' },
        p5: { name: 'العناية بالحيوانات الأليفة', description: 'حيوانات سعيدة، حياة سعيدة! عناية احترافية لصديقك الأليف.' },
        e1: { name: 'تخطيط الفعاليات', description: 'من البداية إلى النهاية، سنجعل مناسبتك لا تُنسى.' },
        e2: { name: 'خدمات التموين', description: 'طعام لذيذ سيكون حديث الحفلة.' },
        e3: { name: 'التصوير الفوتوغرافي والفيديو', description: 'التقاط لحظاتك الثمينة بشكل جميل.' },
        e4: { name: 'خدمات الدي جي والموسيقى', description: 'خلق الأجواء المثالية لأي مناسبة.' },
        e5: { name: 'تزيين القاعات', description: 'تحويل أي مساحة إلى مكان أحلامك.' },
        t1: { name: 'غسيل وتلميع السيارات', description: 'اجعل سيارتك تبدو جديدة تمامًا، من الداخل والخارج.' },
        t2: { name: 'مشاركة الركوب', description: 'رحلات مريحة وصديقة للبيئة عندما تحتاج إليها.' },
        t3: { name: 'خدمات النقل والتغليف', description: 'انتقال سلس وخالٍ من الإجهاد يتم التعامل معه بواسطة محترفين.' },
        t4: { name: 'إصلاح وصيانة الدراجات', description: 'أعد دراجتك إلى الطريق في أفضل حالة.' },
        ed1: { name: 'دروس خصوصية ومساعدة في الواجبات', description: 'دعم ودي لمساعدة الطلاب على النجاح.' },
        ed2: { name: 'دروس لغات', description: 'افتح عالمًا جديدًا بتعلم لغة جديدة.' },
        ed3: { name: 'دروس موسيقى', description: 'اكتشف الموسيقي بداخلك بتوجيه من الخبراء.' },
        ed4: { name: 'فصول الفن والحرف اليدوية', description: 'أطلق العنان لإبداعك في فصل ممتع وملهم.' },
        pr1: { name: 'استشارات قانونية', description: 'مشورة قانونية واضحة وخبيرة يمكنك الوثوق بها.' },
        pr2: { name: 'المحاسبة ومسك الدفاتر', description: 'دعنا نتعامل مع الأرقام حتى تتمكن من التركيز على عملك.' },
        pr3: { name: 'استشارات الأعمال', description: 'رؤى استراتيجية لمساعدة عملك على النمو.' },
        pr4: { name: 'تصميم الجرافيك والعلامات التجارية', description: 'أنشئ هوية تجارية مذهلة تبرز.' },
        hw1: { name: 'استشارات التغذية والحمية', description: 'خطة شخصية من أجل صحة وسعادة أكبر.' },
        hw2: { name: 'فصول اليوغا والتأمل', description: 'ابحث عن توازنك وسلامك الداخلي من خلال فصولنا.' },
        hw3: { name: 'الرعاية التمريضية المنزلية', description: 'رعاية رحيمة ومهنية في المنزل.' },
        hw4: { name: 'خدمات العلاج والاستشارات النفسية', description: 'دعم سري لرفاهيتك النفسية.' },
        tech1: { name: 'دعم وإصلاح تكنولوجيا المعلومات', description: 'حلول سريعة وموثوقة لمشاكلك التقنية.' },
        tech2: { name: 'تطوير وتصميم الويب', description: 'بناء موقع الويب الجميل والوظيفي الذي تحلم به.' },
        tech3: { name: 'التسويق الرقمي', description: 'عزز وجودك على الإنترنت والوصول إلى المزيد من العملاء.' },
        tech4: { name: 'تطوير التطبيقات', description: 'حوّل فكرة تطبيقك الرائعة إلى حقيقة مع فريقنا.' },
        c1: { name: 'صنع كيك مخصص', description: 'كعكات لذيذة ومصممة خصيصًا لأي احتفال.' },
        c2: { name: 'الخياطة والتعديلات', description: 'ملابس مناسبة تمامًا، من أجلك فقط.' },
        c3: { name: 'الديكور الداخلي', description: 'جدد مساحتك بلمسة إبداعية احترافية.' },
        c4: { name: 'لوحات فنية بالطلب', description: 'امتلك قطعة فنية فريدة تم إنشاؤها من أجلك فقط.' },
    },
    serviceList: {
      back: 'العودة إلى الفئات',
      request: 'اطلب',
    },
    detailsForm: {
      back: 'العودة إلى الخدمات',
      title: 'يرجى تقديم تفاصيل طلب الخدمة الخاص بك.',
      locationLabel: 'الموقع',
      locationPlaceholder: 'مثال: 123 شارع رئيسي، الدار البيضاء',
      dateLabel: 'التاريخ',
      timeLabel: 'الوقت',
      notesLabel: 'تعليقات / ملاحظات خاصة',
      notesPlaceholder: 'مثال: يرجى إحضار لوازم التنظيف الخاصة بك.',
      photoLabel: 'تحميل صورة (اختياري)',
      photoButton: 'اختر ملف',
      submit: 'احصل على عرض سعر',
    },
    customRequestForm: {
      back: 'العودة إلى الفئات',
      title: 'طلب خدمة مخصصة',
      subtitle: 'ألم تجد ما تبحث عنه؟ صفه أدناه وسنعود إليك بعرض أسعار.',
      notesLabel: 'صف الخدمة التي تحتاجها',
      notesPlaceholder: 'يرجى تقديم أكبر قدر ممكن من التفاصيل...',
      photoLabel: 'تحميل صورة (اختياري)',
      photoButton: 'اختر ملف',
      submit: 'إرسال طلب مخصص',
    },
    awaitingQuote: {
        title: 'تم استلام الطلب!',
        subtitle: 'نحن نقوم بإعداد عرض السعر الخاص بك وسنعلمك قريبًا عندما يكون جاهزًا. قد يستغرق هذا بضع لحظات.',
    },
    quote: {
        title: 'عرض السعر الخاص بك جاهز!',
        subtitle: 'يرجى مراجعة التفاصيل أدناه. للتأكيد، يرجى إجراء تحويل بنكي للدفع المسبق.',
        service: 'الخدمة',
        whenWhere: 'الزمان والمكان',
        totalPrice: 'السعر الإجمالي',
        timeframe: 'الوقت المقدر',
        depositTitle: 'تفاصيل التحويل البنكي',
        depositInstructions: 'يرجى تحويل المبلغ الإجمالي إلى الحساب البنكي التالي:',
        ribLabel: 'رقم الحساب (RIB)',
        ribNumber: '99089786768688',
        confirmButton: 'لقد قمت بالتحويل',
    },
    confirmed: {
        title: 'تم تأكيد الحجز!',
        subtitle: 'شكرا للدفع. سنتصل بك قريبًا عبر التطبيق أو الهاتف لتزويدك بتفاصيل مقدم الخدمة. سيتم الآن إعادتك إلى الشاشة الرئيسية.',
    },
     profile: {
        back: 'العودة للرئيسية',
        title: 'ملفي الشخصي',
        totalOrders: 'إجمالي الطلبات',
        loginTitle: 'تسجيل الدخول أو الاشتراك',
        emailLabel: 'البريد الإلكتروني',
        passwordLabel: 'كلمة المرور',
        loginButton: 'تسجيل الدخول',
        logoutButton: 'تسجيل الخروج',
        or: 'أو',
        google: 'المتابعة باستخدام جوجل',
        facebook: 'المتابعة باستخدام فيسبوك'
    }
  },
};

export const getTranslations = (lang: Language) => translations[lang];